# имя, отображаемое в интерфейсе
name: 'test my project'
on: [push] # список событий, на которые запускается действие
jobs: # список работ, которые будут производиться (каждая работа будет выводиться отдельно)
 checks: # имя работы сhecks
    runs-on: ubuntu-latest
    steps:
      - name: Begin
        uses: actions/checkout@v3
      - name: Echo hello
        run: echo "hello world"
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: install
        run: pip install -r requirements.txt
      - name: Start tests
        run:  python -m pytest test.py
